const category = '2Blocks'
const height = '60px'
const width = '70px'
import { images } from './images'

const blocks = [
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[0]} />`,
    category: category,
    content: `<div id="ijafq4"><div id="ihubut">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में</div><div id="i7zfnm"><b id="i543j6">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</b></div><div id="igo4uq"><div id="iyyrqk"><div id="izjkpd"><b>ब्रेकिंग न्यूज़</b> | जयपुर</div><div id="ipoyft">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं</div></div><div id="i3iufd"><div id="ibyd8" class="qsection"><div id="i9466"><span id="i6bib">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक </span></div><div id="ienqv"><span id="i0urk"><b>जयपुर</b> | </span>धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं </div></div><div id="ir3e56">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है </div></div></div></div>
    <style>
    #i9466{padding:5px;font-size:medium;text-align:center;font-weight:600;}#ienqv{padding:5px;font-size:small;text-align:justify;}#ibyd8{min-height:90px;padding:5px;background-color:#fff9da;color:black;border:0 solid black;}#i0urk{text-align:center;}#ir3e56{padding:5px;font-size:small;text-align:justify;}#izjkpd{padding:5px;text-align:center;border:0px dashed black;border-width:0px 0px 1px 0px;font-size:small;}#ipoyft{padding:5px;font-size:small;text-align:justify;}#ir3e56{padding:5px 10px 5px 10px;}#ihubut{padding:5px;font-size:medium;color:#484848;border:0 solid black;text-align:center;}#i7zfnm{padding:5px;font-size:X-large;line-height:32px;text-align:justify;}#ipoyft{padding:5px 10px 5px 10px;}#iyyrqk{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i3iufd{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#igo4uq{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#ijafq4{min-height:75px;flex-grow:1;flex-basis:32%;padding:0px 5px 0px 5px;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[1]} />`,
    category: category,
    content: `<div id="iuvxu2"><div id="i51mnj">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में</div><div id="i6z5lo"><b>साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</b></div><div id="ingeri"><div id="ixhzr9"><div id="iar5ud"><b>ब्रेकिंग न्यूज़</b> | जयपुर</div><div id="i4qq7u"> धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं </div></div><div id="ivdl9e"><div id="icltmy">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div></div></div>
    <style>
    #iar5ud{padding:5px;text-align:center;border:0px dashed black;border-width:0px 0px 1px 0px;font-size:small;}#i4qq7u{padding:5px;font-size:small;text-align:justify;}#icltmy{padding:5px;font-size:small;text-align:justify;}#iuvxu2{min-height:75px;flex-grow:1;flex-basis:32%;padding:0px 5px 0px 5px;}#i51mnj{padding:5px;font-size:medium;color:#484848;border:0 solid black;text-align:center;}#i6z5lo{padding:5px;font-size:X-large;line-height:32px;text-align:justify;}#i4qq7u{padding:5px 10px 5px 10px;}#ixhzr9{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#icltmy{padding:5px 10px 5px 10px;}#ivdl9e{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#ingeri{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[2]} />`,
    category: category,
    content: `<div id="iil7m"><div id="ib4sg">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में</div><div id="iwcpoh"><b id="infu3v">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</b></div><div id="io0s5"><div id="ihsxf"><div id="irsgkd"><b>धारा</b> 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div><div id="ihq37"><div id="i3zrdi">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div></div></div>
    <style>
    #i3zrdi{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#irsgkd{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#iil7m{min-height:75px;flex-grow:1;flex-basis:32%;padding:0px 5px 0px 5px;color:black;border:0 solid black;}#ib4sg{padding:5px;font-size:medium;color:#484848;border:0 solid black;text-align:center;}#io0s5{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#ihsxf{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#ihq37{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#iwcpoh{padding:5px;font-size:X-large;line-height:32px;text-align:justify;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[3]} />`,
    category: category,
    content: `<div id="i8grdz"><div id="io3y6"><b id="iqeeu">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा </b></div><img id="irne9z" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3R5bGU9ImZpbGw6IHJnYmEoMCwwLDAsMC4xNSk7IHRyYW5zZm9ybTogc2NhbGUoMC43NSkiPgogICAgICAgIDxwYXRoIGQ9Ik04LjUgMTMuNWwyLjUgMyAzLjUtNC41IDQuNSA2SDVtMTYgMVY1YTIgMiAwIDAgMC0yLTJINWMtMS4xIDAtMiAuOS0yIDJ2MTRjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+"/><div id="itcpjj"><b>धारा</b> 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div>
    <style>
    #itcpjj{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#io3y6{padding:5px;font-size:X-large;line-height:32px;text-align:center;}#i8grdz{min-height:75px;flex-grow:1;flex-basis:27%;}#irne9z{color:black;width:393px;height:219px;margin:0px 10px 0px 10px;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[4]} />`,
    category: category,
    content: `<div id="i31i5n"><div id="i17q4g"><b><span id="iroqxg">साझा</span> उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में</b></div><div id="i7xwwh"><b id="i78fmg">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</b></div><div id="inuvsg"><div id="ihfqdv"><div id="i5ltfl"><b>ब्रेकिंग न्यूज़</b> | जयपुर</div><div id="iq2v71"> धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं </div></div><div id="i23ehr"><div id="iyytku">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div></div></div>
    <style>
    #i5ltfl{padding:5px;text-align:center;border:0px dashed black;border-width:0px 0px 1px 0px;font-size:small;}#iq2v71{padding:5px;font-size:small;text-align:justify;}#iyytku{padding:5px;font-size:small;text-align:justify;}#i17q4g{padding:5px 10px 5px 10px;font-size:medium;color:#484848;border:0 solid black;text-align:left;}#iq2v71{padding:5px 10px 5px 10px;}#ihfqdv{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#iyytku{padding:5px 10px 5px 10px;}#i23ehr{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#inuvsg{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#i31i5n{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#iroqxg{color:#ff0000;}#i7xwwh{padding:0px 10px 5px 10px;font-size:X-large;line-height:32px;text-align:justify;color:black;border:0 solid black;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[5]} />`,
    category: category,
    content: `<div id="i3pdja"><div id="ivmg5m"><b><span id="idgnl3">साझा</span> उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में</b></div><div id="im37mt"><b id="iy6mq8">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</b></div><div id="ijaund"><div id="iu45nk"><div id="iq3bxi"><b>ब्रेकिंग न्यूज़</b> | जयपुर</div><div id="i8njvj"> धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं </div></div><div id="igplew"><img id="il758k" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3R5bGU9ImZpbGw6IHJnYmEoMCwwLDAsMC4xNSk7IHRyYW5zZm9ybTogc2NhbGUoMC43NSkiPgogICAgICAgIDxwYXRoIGQ9Ik04LjUgMTMuNWwyLjUgMyAzLjUtNC41IDQuNSA2SDVtMTYgMVY1YTIgMiAwIDAgMC0yLTJINWMtMS4xIDAtMiAuOS0yIDJ2MTRjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+"/><div id="i0zfon">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div></div></div>
    <style>
    #iq3bxi{padding:5px;text-align:center;border:0px dashed black;border-width:0px 0px 1px 0px;font-size:small;}#i8njvj{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#i0zfon{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}{#idgnl3{color:#ff0000;}#ivmg5m{padding:5px 10px 5px 10px;font-size:medium;color:#484848;border:0 solid black;text-align:left;}#iu45nk{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#igplew{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);padding:5px 0 0 0;display:flex;flex-direction:column;justify-content:flex-start;align-items:center;}#ijaund{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#i3pdja{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#il758k{color:black;width:187px;height:112px;}#im37mt{padding:0px 10px 5px 10px;font-size:X-large;line-height:32px;text-align:justify;color:black;border:0 solid black;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[6]} />`,
    category: category,
    content: `<div id="ixbaek"><div id="i8c3s6"><b id="ig2ecm"><span id="i1qtt5">साझा उम्मीदवार</span> पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</b></div><img id="iaenfj" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3R5bGU9ImZpbGw6IHJnYmEoMCwwLDAsMC4xNSk7IHRyYW5zZm9ybTogc2NhbGUoMC43NSkiPgogICAgICAgIDxwYXRoIGQ9Ik04LjUgMTMuNWwyLjUgMyAzLjUtNC41IDQuNSA2SDVtMTYgMVY1YTIgMiAwIDAgMC0yLTJINWMtMS4xIDAtMiAuOS0yIDJ2MTRjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+"/><div id="iqs20b"><div id="i7d3xe"><div id="ixc9kl"><b>धारा</b> 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div><div id="iatu97"><div id="iei7fu"><b>धारा</b> 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div></div></div>
    <style>
    #iei7fu{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#ixc9kl{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#i8c3s6{padding:0px 10px 5px 10px;font-size:X-large;line-height:32px;text-align:justify;color:black;border:0 solid black;}#ixbaek{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);align-items:center;}#i1qtt5{color:#ff0000;}#iaenfj{color:black;width:406px;height:179px;opacity:1;}#iqs20b{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#i7d3xe{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#iatu97{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[7]} />`,
    category: category,
    content: `<div id="iq5lvb"><div id="idt4qe"><b id="i4vbou">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</b></div><div id="i6io2p"><div id="ine0y1"><div id="ioehgj">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div><div id="i0aqpo"><div id="ik2nj4">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div></div></div>
    <style>
    #ioehgj{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#ik2nj4{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#idt4qe{padding:0px 10px 5px 10px;font-size:X-large;line-height:32px;text-align:justify;color:black;border:0 solid black;}#iq5lvb{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#i6io2p{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#ine0y1{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i0aqpo{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[8]} />`,
    category: category,
    content: `<div id="i52asi"><div id="ignrky"><img id="ihn6vv" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3R5bGU9ImZpbGw6IHJnYmEoMCwwLDAsMC4xNSk7IHRyYW5zZm9ybTogc2NhbGUoMC43NSkiPgogICAgICAgIDxwYXRoIGQ9Ik04LjUgMTMuNWwyLjUgMyAzLjUtNC41IDQuNSA2SDVtMTYgMVY1YTIgMiAwIDAgMC0yLTJINWMtMS4xIDAtMiAuOS0yIDJ2MTRjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+"/></div><div id="ikkdqi"><div id="indqbp">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div></div>
    <style>
    #indqbp{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#i52asi{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;background-color:#fff0cc;}#ignrky{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#ikkdqi{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#ihn6vv{color:black;width:201px;height:208px;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[9]} />`,
    category: category,
    content: `<div id="i6io2p"><div id="ine0y1"><div id="ioehgj">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div><div id="i0aqpo"><div id="ik2nj4">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं  ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- </div></div></div>
    <style>
    #ioehgj{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#ik2nj4{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#i6io2p{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#ine0y1{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i0aqpo{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}
    </style>`
  },
]

export default blocks
