const category = '2Blocks'
const height = '60px'
const width = '70px'
import { images } from './images'

const blocks = [
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[0]} />`,
    category: category,
    content: `<div id="it81d"><img id="iwts3" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3R5bGU9ImZpbGw6IHJnYmEoMCwwLDAsMC4xNSk7IHRyYW5zZm9ybTogc2NhbGUoMC43NSkiPgogICAgICAgIDxwYXRoIGQ9Ik04LjUgMTMuNWwyLjUgMyAzLjUtNC41IDQuNSA2SDVtMTYgMVY1YTIgMiAwIDAgMC0yLTJINWMtMS4xIDAtMiAuOS0yIDJ2MTRjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+"/><div id="iqqtz"><span id="igblj">उधर गृहमंत्री अमित शाह ने विपक्षी एकता पर तंज कसा- विपक्ष कभी एक होने वाला नहीं है। पटना में तो विपक्षी नेताओं का फ़ोटो सेशन चल रहा है। इससे ज़्यादा या अलग कुछ नहीं।</span></div></div>
    <style>
    #it81d{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#iwts3{color:black;width:403px;height:317px;}#iqqtz{padding:10px 10px 10px 10px;font-size:small;background-color:#fff5d8;}#igblj{font-weight:normal;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[1]} />`,
    category: category,
    content: `<div id="ido6ul"><div id="ixi94i">इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर</div><b id="i4hykd">इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे</b><div id="ij9sbo"><div id="ip7qnj"><div id="i1f24g"><span id="igcqgh"><b id="ic0ooi">भास्कर न्यूज |</b> कोचिन्ग/ जैपुर </span></div><div id="i8k4rm"><b id="i7oj5n-2" draggable="true">इस मीटिंग |</b><span id="isc0dc"> को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। अब्दुल्ला ने तो इस मीटिंग में ही आप पार्टी पर तंज कस दिया कि धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं </span></div></div><div id="i9s4a4"><div id="idny3j"><div id="iinmn7"><div id="ix5m5b"><b id="iltozp">उधर गृहमंत्री अमित शाह ने विपक्षी एकता पर तंज कसा</b></div><div id="ildze2"><span id="irubws">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं</span><br/></div></div></div><div id="ivtykr"><span id="ia361h">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं</span></div></div></div><div id="ittdrh"></div></div>
    <style>
    #i8k4rm{padding:5px 10px 5px 0px;text-align:left;}#i7oj5n-2{font-size:small;}#isc0dc{font-size:small;text-align:left;}#ido6ul{min-height:75px;flex-grow:1;flex-basis:61%;}#ixi94i{padding:5px 10px 10px 10px;text-align:center;color:#383636;}#ittdrh{padding:5px 10px 5px 10px;text-align:center;font-size:19px;}#i4hykd{padding:5px 0px 5px 0px;font-size:large;}#ij9sbo{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;padding:0px 0px 0px 0px;}#ip7qnj{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);padding:5px 0 0 0;}#i9s4a4{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#igcqgh{font-weight:normal;text-align:center;font-size:small;}#i1f24g{padding:5px 10px 5px 10px;color:#3e3e3e;text-align:center;border:0px dotted #191919;border-width:0px 0px 2px 0px;}#idny3j{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;padding:10px 10px 10px 10px;background-color:#fff5d8;}#iinmn7{min-height:75px;flex-grow:1;flex-basis:calc(100% / 1);}#ix5m5b{padding:5px 10px 5px 10px;text-align:left;}#ildze2{padding:5px 10px 5px 10px;text-align:left;}#irubws{font-size:small;}#ivtykr{padding:10px;margin:10px 0 0 0;}#ia361h{font-size:small;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[2]} />`,
    category: category,
    content: `<div id="itah3h"><div id="i095wg">इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार</div><b id="it1p24">इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे</b><div id="i6877f"><div id="i3779u"><div id="i5slpg"><span id="i1jgdt"><b id="ikygwv">भास्कर न्यूज |</b> कोचिन्ग/ जैपुर </span></div><div id="i8j72y"><span id="i1kqaf">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं</span></div></div><div id="i6iol1"><div id="i6o2jf"><b draggable="true" id="i12ple">इस मीटिंग |</b><span id="iriq2q"> को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं।</span></div></div></div></div>
    <style>
    #itah3h{min-height:75px;flex-grow:1;flex-basis:92%;}#i095wg{padding:5px 10px 10px 10px;text-align:center;color:#383636;}#it1p24{padding:5px 0px 5px 0px;margin:0 0 10px 0;font-size:large;}#i6877f{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;padding:5px;}#i3779u{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i6iol1{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i1jgdt{font-weight:normal;text-align:center;font-size:small;}#i5slpg{padding:5px 10px 5px 10px;color:#3e3e3e;text-align:center;border:0px dotted #191919;border-width:0px 0px 2px 0px;}#i1kqaf{font-size:small;}#i8j72y{padding:10px 0px 10px 0px;margin:0px 0px 0px 0px;}#i12ple{font-size:small;}#iriq2q{font-size:small;text-align:left;}#i6o2jf{padding:5px 0px 5px 10px;text-align:left;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[3]} />`,
    category: category,
    content: `<div id="i6877f"><div id="i3779u"><div id="i5slpg"><span id="i1jgdt"><b id="ikygwv">भास्कर न्यूज |</b> कोचिन्ग/ जैपुर </span></div><div id="i8j72y"><span id="i1kqaf">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं</span></div></div><div id="i6iol1"><div id="i6o2jf"><b draggable="true" id="i12ple">इस मीटिंग |</b><span id="iriq2q"> को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं।</span></div></div></div>
    <style>
    #i6877f{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;padding:5px;}#i3779u{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i6iol1{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i1jgdt{font-weight:normal;text-align:center;font-size:small;}#i5slpg{padding:5px 10px 5px 10px;color:#3e3e3e;text-align:center;border:0px dotted #191919;border-width:0px 0px 2px 0px;}#i1kqaf{font-size:small;}#i8j72y{padding:10px 0px 10px 0px;margin:0px 0px 0px 0px;}#i12ple{font-size:small;}#iriq2q{font-size:small;text-align:left;}#i6o2jf{padding:5px 0px 5px 10px;text-align:left;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[4]} />`,
    category: category,
    content: `<div id="i4vrb4"><div id="icksxx"><span id="i28zr8">भगवान जगन्नाथ, बहन सुभद्रा और बड़े भाई बलदाऊ, </span><span id="ixsbc1">भगवान जगन्नाथ, बहन सुभद्रा और बड़े भाई बलदाऊ</span></div><div id="ixjajd"><div id="i8ptov"><div id="ibcwsn"><b draggable="true" id="ijbl8c">इस मीटिंग |</b><span id="ihhg8o"> को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। अब्दुल्ला ने तो इस मीटिंग में ही आप पार्टी पर तंज कस दिया कि</span></div></div><div id="id4auv"><div id="imd4fw"><span id="i9fm3o"> धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं </span></div></div></div></div>
    <style>
    #i4vrb4{min-height:75px;flex-grow:1;flex-basis:29%;}#icksxx{padding:10px;font-size:large;}#i28zr8{font-weight:600;text-align:center;}#ixsbc1{font-weight:600;text-align:center;}#ixjajd{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;padding:0px 5px 0px 5px;}#i8ptov{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#id4auv{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#ijbl8c{font-size:small;}#ihhg8o{font-size:small;text-align:left;}#ibcwsn{padding:5px 0px 5px 0px;text-align:left;}#imd4fw{padding:5px 0px 10px 10px;}#i9fm3o{font-size:small;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[5]} />`,
    category: category,
    content: `<div id="if7ixz"><div id="i47fa1"><span id="ihl79v"><b>भगवान</b></span> जगन्नाथ की नगरी पुरी इन दिनों गुलजार है</div><div id="iex3w1">भगवान जगन्नाथ की नगरी पुरी इन दिनों गुलजार है। ये रथयात्रा का असर है</div><div id="icuo3p"><div id="i6jbwg"><div id="ivm5bl"><span id="i2z2jh"><b id="iboqyp">भास्कर न्यूज |</b> कोचिन्ग/ जैपुर </span></div><div id="ipufr4"><span id="i13rnk"> धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं </span></div></div><div id="ik0dh2"><div id="is7jng"><span id="ihhwh8"> धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं </span><span id="iwpx7j">ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके</span></div></div></div></div>
    <style>
    #if7ixz{min-height:75px;flex-grow:1;flex-basis:29%;}#i47fa1{padding:5px 10px 5px 10px;font-weight:600;color:#5d5353;}#ihl79v{font-weight:normal;color:#ff0000;}#iex3w1{padding:5px 10px 5px 10px;font-weight:700;font-size:x-large;}#icuo3p{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;padding:5px;}#i6jbwg{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#ik0dh2{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i2z2jh{font-weight:normal;text-align:center;}#ivm5bl{padding:5px 10px 5px 10px;color:#3e3e3e;text-align:center;border:0px dotted #191919;border-width:0px 0px 2px 0px;}#i13rnk{font-size:small;}#ipufr4{padding:10px 0px 10px 0px;}#ihhwh8{font-size:small;}#is7jng{padding:10px;}#iwpx7j{font-size:small;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[6]} />`,
    category: category,
    content: `<div id="iw6s6h"><div id="igdj41">बिना बताए मौसी के घर जाने से गुस्सा, पुजारी ने बताया क्या है</div><div id="iywusq"><span draggable="true" id="i69ldj">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। </span><span id="iidmkl">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं।</span><span id="ijiunu">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं।</span><span id="iryn2u">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। </span></div></div>
    <style>
   #igdj41{padding:5px 10px 5px 10px;font-weight:600;font-size:large;text-align:left;}#iw6s6h{min-height:75px;flex-grow:1;flex-basis:calc(100% / 4);}#i69ldj{font-size:small;}#iidmkl{font-size:small;}#ijiunu{font-size:small;}#iryn2u{font-size:small;}#iywusq{padding:10px;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[7]} />`,
    category: category,
    content: `<div id="ihschi"><div id="iy1dgw">आज भगवान जगन्नाथ का रथ तोड़ेंगी लक्ष्मीजी:<br/>बिना बताए मौसी के</div><img id="i3rdsc" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zd…RjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+"/><div id="i0eszj"><span draggable="true" id="i1jycm">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। </span><span id="iigvb3">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं।</span><span id="iw9wdl">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं।</span><span id="iix2ds">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। </span></div></div>
    <style>
   #ihschi{min-height:75px;flex-grow:1;flex-basis:88%;}#iy1dgw{padding:5px 10px 5px 10px;font-weight:600;font-size:large;text-align:center;}#i3rdsc{color:black;width:409px;height:172px;}#i1jycm{font-size:small;}#iigvb3{font-size:small;}#iw9wdl{font-size:small;}#iix2ds{font-size:small;}#i0eszj{padding:10px;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[8]} />`,
    category: category,
    content: `<div id="ixjqhc"><img id="ilryho" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3R5bGU9ImZpbGw6IHJnYmEoMCwwLDAsMC4xNSk7IHRyYW5zZm9ybTogc2NhbGUoMC43NSkiPgogICAgICAgIDxwYXRoIGQ9Ik04LjUgMTMuNWwyLjUgMyAzLjUtNC41IDQuNSA2SDVtMTYgMVY1YTIgMiAwIDAgMC0yLTJINWMtMS4xIDAtMiAuOS0yIDJ2MTRjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+"/><div id="i1j6xl"><div id="i76yc7"><div id="i9uznl"><span draggable="true" id="ixfseb">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। </span><span id="iooxe4">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं।</span></div></div><div id="iirulh"><div id="iubo13"><span draggable="true" id="iw4bph">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। </span><span id="iajglh">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं।</span></div></div></div></div>
    <style>
   #ixjqhc{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#ilryho{color:black;width:367px;height:186px;}#i1j6xl{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;padding:0px 0px 0px 0px;}#i76yc7{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#ixfseb{font-size:small;}#iooxe4{font-size:small;}#i9uznl{padding:10px;}#iw4bph{font-size:small;}#iajglh{font-size:small;}#iubo13{padding:10px;}#iirulh{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[9]} />`,
    category: category,
    content: `<div id="idburt"><div id="ikpzax"><div id="igljq4"><b draggable="true" id="i8zxwc">इस मीटिंग |</b><span draggable="true" id="iha36e"> को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। </span><span id="ipdx5x">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। </span></div></div><div id="ixd2px"><div id="ikoxtx"><span draggable="true" id="i8wbf3">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। </span><span id="ilj34g">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है।<br/></span></div></div></div>
    <style>
   #i8zxwc{font-size:small;}#iha36e{font-size:small;}#ipdx5x{font-size:small;}#igljq4{padding:5px 10px 5px 10px;color:black;border:0 solid black;}#ikpzax{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i8wbf3{font-size:small;}#ilj34g{font-size:small;}#ikoxtx{padding:5px 10px 5px 10px;}#ixd2px{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#idburt{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[10]} />`,
    category: category,
    content: `<div id="ig6bwu"><div id="iug5v2">इधर-उधर देखा तो आसन से कुछ</div><div id="ijxdj4">इधर-उधर देखा तो आसन से कुछ आगे दो मूर्तियों पर नजर गई पुजारियों से पूछा तो पता चला</div><div id="idburt"><div id="ikpzax"><div id="igljq4"><b draggable="true" id="i8zxwc">इस मीटिंग |</b><span draggable="true" id="iha36e"> को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। </span><span id="ipdx5x">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। </span></div></div><div id="ixd2px"><div id="ikoxtx"><span draggable="true" id="i8wbf3">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। </span><span id="ilj34g">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है।<br/></span></div></div></div></div>
    <style>
   #ig6bwu{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#iug5v2{padding:5px 10px 5px 10px;font-size:large;font-weight:700;text-align:center;color:red;}#ijxdj4{padding:5px 10px 5px 10px;font-size:x-large;font-weight:700;}#i8zxwc{font-size:small;}#iha36e{font-size:small;}#ipdx5x{font-size:small;}#igljq4{padding:5px 10px 5px 10px;color:black;border:0 solid black;}#ikpzax{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i8wbf3{font-size:small;}#ilj34g{font-size:small;}#ikoxtx{padding:5px 10px 5px 10px;}#ixd2px{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#idburt{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[11]} />`,
    category: category,
    content: `<div id="i5ekwp"><div id="imzrza">इधर-उधर देखा तो आसन से कुछ आगे दो मूर्तियों पर नजर गई पुजारियों से पूछा तो पता चला</div><div id="i5dw3l"><div id="ixei2h"><div id="isa9wy"><b draggable="true" id="ieu0mt">इस मीटिंग |</b><span draggable="true" id="ibwxrm"> को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। </span><span id="itgrb5">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। </span></div></div><div id="i1kv49"><div id="il8uw8"><span draggable="true" id="ihg6p2">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं जिनसे ये कभी समझौता नहीं कर सकतीं। </span><span id="i0rgue">को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है।<br/></span></div></div></div></div>
    <style>
   #i5ekwp{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#imzrza{padding:5px 10px 5px 10px;font-size:x-large;font-weight:700;}#i5dw3l{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#ixei2h{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i1kv49{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#ieu0mt{font-size:small;}#ibwxrm{font-size:small;}#itgrb5{font-size:small;}#isa9wy{padding:5px 10px 5px 10px;color:black;border:0 solid black;}#ihg6p2{font-size:small;}#i0rgue{font-size:small;}#il8uw8{padding:5px 10px 5px 10px;}
    </style>`
  }
]

export default blocks
