const category = '3Blocks'
const height = '60px'
const width = '70px'
import { images } from './images'

const blocks = [
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[0]} />`,
    category: category,
    content: `<div id="izve74"><div id="i4swea"><h3 id="iru1s4"><b>साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली </b><b draggable="true">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</b></h3><div id="i6y36s"><div id="i4enx3"><div id="iros28"><b id="i9vtmy">ब्रेकिंग न्यूज़</b> | जयपुर</div><div id="iuvx2q">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं राज्यों में इनके अपने- अ</div></div><div id="iusm53"><div id="id1jri">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं</div></div><div id="ijet1p"><div id="i43wq5">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं</div></div></div></div></div>
    <style>
    #i4swea{min-height:75px;flex-grow:1;flex-basis:49%;padding:10px 0 0 0;}#i6y36s{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#i4enx3{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);display:flex;flex-direction:column;align-items:center;}#iusm53{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#ijet1p{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#iros28{padding:5px;font-size:small;text-align:center;border:0px dashed black;border-width:0px 0px 1px 0px;}#iuvx2q{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#izve74{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#id1jri{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#iru1s4{padding:5px;}#i43wq5{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[1]} />`,
    category: category,
    content: `<div id="ip1471"><h3 id="ibicv8"><b id="i9llci">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली </b><b id="ioa31x" draggable="true">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</b></h3><div id="i1dp1k"><div id="ixreg2"><div id="i14ur5">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं</div></div><div id="iwi5ks"><img id="i1ff9c" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3R5bGU9ImZpbGw6IHJnYmEoMCwwLDAsMC4xNSk7IHRyYW5zZm9ybTogc2NhbGUoMC43NSkiPgogICAgICAgIDxwYXRoIGQ9Ik04LjUgMTMuNWwyLjUgMyAzLjUtNC41IDQuNSA2SDVtMTYgMVY1YTIgMiAwIDAgMC0yLTJINWMtMS4xIDAtMiAuOS0yIDJ2MTRjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+"/><div id="izlm4b"><div id="iozcpr"><div id="io10nn">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं</div></div><div id="imwb2o"><div id="i5rihr">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं</div></div></div></div></div></div>
    <style>
    #ibicv8{padding:5px;}#i14ur5{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#ip1471{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i1dp1k{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#ixreg2{min-height:75px;flex-grow:1;flex-basis:13%;}#iwi5ks{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i1ff9c{color:black;width:412px;height:202px;}#izlm4b{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#iozcpr{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#imwb2o{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i5rihr{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#io10nn{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[2]} />`,
    category: category,
    content: `<div id="itq2aw"><h3 id="itza3g"><b>साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली </b><b draggable="true">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</b></h3><div id="ihy138"><div id="ifz8ea"><img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3R5bGU9ImZpbGw6IHJnYmEoMCwwLDAsMC4xNSk7IHRyYW5zZm9ybTogc2NhbGUoMC43NSkiPgogICAgICAgIDxwYXRoIGQ9Ik04LjUgMTMuNWwyLjUgMyAzLjUtNC41IDQuNSA2SDVtMTYgMVY1YTIgMiAwIDAgMC0yLTJINWMtMS4xIDAtMiAuOS0yIDJ2MTRjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+" id="itk05p"/></div><div id="itxek3"><div id="i7y56c"><b>ब्रेकिंग न्यूज़</b> | जयपुर</div><div id="im2hdn">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं राज्यों में इनके अपने- अ</div></div><div id="i915aj"><div id="idfuqu">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं</div></div></div></div>
    <style>
    #itq2aw{min-height:75px;flex-grow:1;flex-basis:49%;padding:10px 0 0 0;}#itza3g{padding:5px;}#itk05p{color:black;width:194px;height:274px;}#ifz8ea{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);display:flex;flex-direction:column;align-items:center;}#i7y56c{padding:5px;font-size:small;text-align:center;border:0px dashed black;border-width:0px 0px 1px 0px;}#im2hdn{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#itxek3{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#idfuqu{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#i915aj{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#ihy138{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[3]} />`,
    category: category,
    content: `<div id="i93l0z"><div id="i9i6r5"><img id="iq99z6" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3R5bGU9ImZpbGw6IHJnYmEoMCwwLDAsMC4xNSk7IHRyYW5zZm9ybTogc2NhbGUoMC43NSkiPgogICAgICAgIDxwYXRoIGQ9Ik04LjUgMTMuNWwyLjUgMyAzLjUtNC41IDQuNSA2SDVtMTYgMVY1YTIgMiAwIDAgMC0yLTJINWMtMS4xIDAtMiAuOS0yIDJ2MTRjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+"/><div id="i9hv7n">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग</div></div><div id="iukvsl"><div id="idh2og">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैंराज्यों में इनके अपने- अपने हित हैं </div></div></div>
    <style>
    #i9hv7n{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#i93l0z{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#i9i6r5{min-height:75px;flex-grow:1;flex-basis:110%;}#iukvsl{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#iq99z6{color:black;width:414px;height:283px;}#idh2og{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[4]} />`,
    category: category,
    content: `<div id="iyq972"><h2 id="ixieqh"><b id="iivkzg">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली </b><b draggable="true" id="iuv3h5">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति</b></h2><h4 id="iyujov">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</h4><div id="izcdol"><div id="i8gywp"><div id="itsrmg"><b>ब्रेकिंग न्यूज़</b> | जयपुर</div><div id="izbilh">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं राज्यों में इनके अपने- अ</div></div><div id="i2x2cf"><div id="iv8ndf">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं</div></div><div id="ivq61h"><div id="i74xd2">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं</div></div></div></div>
    <style>
    #itsrmg{padding:5px;font-size:small;text-align:center;border:0px dashed black;border-width:0px 0px 1px 0px;}#izbilh{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#i8gywp{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#i2x2cf{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#izcdol{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#iyq972{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#i74xd2{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#ivq61h{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#iyujov{padding:0px 10px 0px 10px;}#iv8ndf{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#ixieqh{padding:5px 5px 0px 5px;color:black;border:0 solid black;}
    </style>`
  },
  {
    media: `<img height=${height} width=${width} class="firstBlockImages" src=${images[5]} />`,
    category: category,
    content: `<div id="ivjaud"><div id="i19r7h">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली</div><h2 id="iaxb8g"><b id="iem7u3">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति, भाजपा में खलबली </b><b id="iyibo5" draggable="true">साझा उम्मीदवार पर विपक्षी पार्टियों में प्राथमिक सहमति</b></h2><div id="iro5i3"><div id="irs9xd"><div id="i5vgc9"><b>ब्रेकिंग न्यूज़</b> | जयपुर</div><div id="iu1zu6">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं राज्यों में इनके अपने- अ</div></div><div id="it5up6"><img id="i58d6i" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIHZpZXdCb3g9IjAgMCAyNCAyNCIgc3R5bGU9ImZpbGw6IHJnYmEoMCwwLDAsMC4xNSk7IHRyYW5zZm9ybTogc2NhbGUoMC43NSkiPgogICAgICAgIDxwYXRoIGQ9Ik04LjUgMTMuNWwyLjUgMyAzLjUtNC41IDQuNSA2SDVtMTYgMVY1YTIgMiAwIDAgMC0yLTJINWMtMS4xIDAtMiAuOS0yIDJ2MTRjMCAxLjEuOSAyIDIgMmgxNGMxLjEgMCAyLS45IDItMnoiPjwvcGF0aD4KICAgICAgPC9zdmc+"/><div id="iw5h0t">कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं राज्यों में इनके अपने- अ</div></div><div id="ihwk9g"><div id="ivlmac">धारा 370 पर आप के रुख़ को लेकर मैं आश्चर्यचकित हूँ। इस मीटिंग को लेकर कई भाजपा नेताओं ने नीतीश कुमार और ख़ासकर, कांग्रेस के खिलाफ खूब तंज कसे, उनका कहना है कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं कि विपक्षी एकता सिर्फ़ दिखावा है। ये पार्टियाँ कभी एक नहीं हो सकतीं क्योंकि अलग- अलग राज्यों में इनके अपने- अपने हित हैं अलग राज्यों में इनके अपने- अपने हित हैं</div></div></div></div>
    <style>
    #ivjaud{min-height:75px;flex-grow:1;flex-basis:calc(100% / 2);}#iaxb8g{padding:5px 5px 0px 5px;color:black;border:0 solid black;text-align:center;}#i5vgc9{padding:5px;font-size:small;text-align:center;border:0px dashed black;border-width:0px 0px 1px 0px;}#iu1zu6{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#irs9xd{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#ivlmac{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#ihwk9g{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#iro5i3{display:flex;justify-content:flex-start;align-items:stretch;flex-wrap:nowrap;}#i19r7h{padding:5px;font-size:19px;text-align:center;color:#4a4a4a;font-weight:600;}#iw5h0t{padding:5px 10px 5px 10px;font-size:small;text-align:justify;}#it5up6{min-height:75px;flex-grow:1;flex-basis:calc(100% / 3);}#i58d6i{color:black;width:204px;height:142px;}
    </style>`
  },
]

export default blocks
